accounts/passwords/urls.py
from django.contrib.auth import views
from django.urls import path

urlpatterns = [
    path(
        "change-password/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "change-password/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("reset-password/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset-done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

accounts/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from shop.views import UserProductHistoryView

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.AccountHomeView.as_view(), name="user-home"),
    path(_("profile/"), views.UserDetailUpdateView.as_view(), name="user-update"),
    path(
        _("history/"),
        UserProductHistoryView.as_view(),
        name="user-product-history",
    ),
    path(
        _("email/confirm/<slug:key>/"),
        views.AccountEmailActivateView.as_view(),
        name="email-activate",
    ),
    path(
        _("email/resend-activation/"),
        views.AccountEmailActivateView.as_view(),
        name="resend-activation",
    ),
]

chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.contact, name="contact"),
    # views.ContactView.as_view(), name="contact"),
    path("<str:room>/", views.room, name="room"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("trademark/", views.TrademarkView.as_view(), name="trademark"),
    path("donate/", views.DonateView.as_view(), name="donate"),
    path("cookie/", views.CookieView.as_view(), name="cookie"),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("terms/", views.TermsView.as_view(), name="terms"),
    path("policy-pdf/<slug:slug>/", views.GeneratePolicyPDF.as_view(), name="policy-pdf"),
]

accounts/models.py
"""
Custom user
Require email instead of username
Consider removing password -> Passwordless
Register -> send email to verify and activate account
Login -> send email every time -> enforce 2fa
"""
from datetime import timedelta

from core.utils import code_gen, unique_key_generator
from disposable_email_checker.validators import validate_disposable_email
from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
# from django.core.validators import EmailValidator
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save, pre_save
from django.template.loader import get_template
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from PIL import Image
from tinymce.models import HTMLField

# https://docs.djangoproject.com/en/3.2/topics/email/
# send_mail(subject, message, from_email, recipient_list, html_message) random_string_generator,

# DEFAULT_ACTIVATION_DAYS = getattr(settings, "DEFAULT_ACTIVATION_DAYS", 7)

# CLVM = getattr(settings, "ENV_NAME", "Clavem")

CURRENCIES = [("€", "EUR"), ("$", "USD")]
# ('£', 'GBP'), Add crypto
# ('$', 'CAD'),
# ('$', 'AUS'),


# class CurrencyType(models.TextChoices):
#     EUR = "€", _("EUR")
#     USD = "$", _("USD")


class UserManager(BaseUserManager):
    # Create and save a User with email and password

    def create_user(
        self, email, password=None, is_staff=False, is_admin=False, **kwargs
    ):  # fn=None, ln=None, is_active=True if email verified
        if not email:
            raise ValueError(_("Please add your email address"))
        if not password:
            raise ValueError(_("Please set your password"))
        # if not fn:
        #     raise ValueError(_("Please add your name"))
        if validate_disposable_email(email):  # validate_email(email):
            e = self.normalize_email(
                email
            )  # self.model(email=self.normalize_email(email))
            user = self.model(email=e, **kwargs)  # , first_name=fn
            user.set_password(password)
            # user.first_name = fn# Use first name to send personalize email
            # user.last_name = ln
            # user.is_staff = staff
            # user.is_active = active
            # user.is_admin = admin
            # user.date_joined.timezone.now()
            user.save(using=self._db)
            return user
        raise ValidationError

    def create_staffuser(
        self, email, password=None, **kwargs
    ):  # first_name=None, last_name=None,
        kwargs.setdefault("is_active", True)
        kwargs.setdefault("is_admin", False)
        kwargs.setdefault("is_staff", True)
        if kwargs.get("is_active") is False:
            raise ValueError(_("Forgot active=True"))
        if kwargs.get("is_staff") is False:
            raise ValueError(_("Forgot staff=True"))
        if kwargs.get("is_admin") is True:
            raise ValueError(_("Staff is not admin"))
        return self.create_user(email, password, first_name, **kwargs)

    def create_admin(self, email, password=None, first_name=None, **kwargs):
        kwargs.setdefault("is_active", True)
        kwargs.setdefault("is_admin", True)
        kwargs.setdefault("is_staff", True)
        if kwargs.get("is_active") is False:
            raise ValueError("Forgot to set is_active=True")
        if kwargs.get("is_staff") is False:
            raise ValueError("Forgot to set is_active=True")
        if kwargs.get("is_admin") is False:  # remove
            raise ValueError("Forgot to set is_admin=True")
        return self.create_user(email, password, first_name, **kwargs)


def usr_img_path(self, filename):
    e = self.email
    u = e[: e.index("@")] + "-" + code_gen(6)  # self.first_name + "-" + self.last_name
    return f"users/{u}/{filename}"

#     d = e[e.index("@") + 1 :]  # get email domain
#     with open("media/temp-emails.txt") as emails:
#         if d in emails.read():
#             raise ValidationError(
#                 _("Temporary emails are not allowed.")  # ,
#                 # params={"email": e},
#             )


class CUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        max_length=99,
        unique=True,
        validators=[
            # EmailValidator(
            #     whitelist=["protonmail", "tutanota", "gmail", "yahoo", "hotmail"]# what about less known valid domains? Better check whether the domain is in the disposable list which has to be weekly updated.
            # )
        ],
    )  # db_index=True
    # username = CharField(max_length=90, unique=True)
    first_name = models.CharField(max_length=99, blank=True, null=True)
    last_name = models.CharField(max_length=99, blank=True, null=True)
    bio = HTMLField(_("Bio"), blank=True, null=True)
    img = models.FileField(
        _("Profile image"), upload_to=usr_img_path, null=True, blank=True
    )
    is_active = models.BooleanField(default=False)  # activation link
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(
        _("Date joined"), auto_now_add=True
    )  # default=timezone.now
    currency = models.CharField(max_length=3, choices=CURRENCIES, default="$")
    # CurrencyType.choices, default=CurrencyType.EUR
    # registered_at = models.DateTimeField(auto_now_add=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name"]  # , "last_name"

    objects = UserManager()

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        abstract = False

    def __str__(self):
        return self.email

    # def get_username(self):
    #     # Consider using email as username
    #     if self.full_name:email
    #        return self.full_name
    #     if self.username:
    #        return self.username
    #     return self.first_name

    def get_full_name(self):
        return str(self.first_name + " " + self.last_name)

    def get_usrname(self):
        e = self.email
        return str(e[: e.index("@")])

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def active(self):
        return self.is_active

    @property
    def admin(self):
        return self.is_admin

    @property
    def staff(self):
        if self.is_admin:
            return True
        return self.is_staff

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.img.path)
        if img.mode in ("RGBA", "P"):
            img = img.convert("RGB")
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.img.path)


class EmailActivationQuerySet(models.query.QuerySet):
    # EmailActivation.objects.all().confirmable()

    def confirmable(self):
        # Does the object have a timestamp
        now = timezone.now()
        start_range = now - timedelta(
            days=getattr(settings, "DEFAULT_ACTIVATION_DAYS", 7)
        )
        end_range = now
        # activated = False
        # forced_expired = False
        return self.filter(activated=False, forced_expired=False).filter(
            created__gt=start_range,  # greater
            created__lte=end_range,  # less or equal
        )


class EmailActivationManager(models.Manager):
    def get_queryset(self):
        return EmailActivationQuerySet(self.model, using=self._db)

    def confirmable(self):
        # EmailActivation.objects.confirmable()
        return self.get_queryset().confirmable()

    def email_exists(self, email):
        # Check if email is present in the database
        return (
            self.get_queryset()
            .filter(Q(email=email) | Q(user__email=email))
            .filter(activated=False)
        )


class EmailActivation(models.Model):
    # Expire after 7 days
    user = models.ForeignKey(CUser, on_delete=models.CASCADE)
    email = models.EmailField()
    key = models.CharField(max_length=120, null=True, blank=True)
    activated = models.BooleanField(default=False)
    forced_expired = models.BooleanField(default=False)
    expires = models.IntegerField(default=7)
    created = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated = models.DateTimeField(_("Updated at"), auto_now=True)

    objects = EmailActivationManager()

    def __str__(self):
        return self.email

    def can_activate(self):
        qs = EmailActivation.objects.filter(pk=self.pk).confirmable()
        if qs.exists():
            return True
        return False

    # def activate(self):
    #     if self.can_activate():
    #         # pre activation user signal
    #         user = self.user
    #         user.is_active = True
    #         user.save()
    #         # post activation signal for user
    #         self.activated = True
    #         self.save()
    #         return True
    #     return False

    def regenerate(self):
        self.key = None
        self.save()
        if self.key is not None:
            return True
        return False

    def send_activation(self):
        if not self.activated and not self.forced_expired:
            if self.key:
                base_url = getattr(settings, "BASE_URL", "https://www.clavem.co/")
                key_path = reverse("account:email-activate", kwargs={"key": self.key})
                path = f"{base_url}/{key_path}"  #'{base}{path}'.format(base=base_url, path=key_path)
                context = {"path": path, "email": self.email}
                subject = (
                    _("Activate your ")

accounts/templates/accounts/edit-profile.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% if title %}{{ title }}{% else %}{% trans 'Edit Profile' %}{% endif %}{% endblock %}
{% block content %}
<div class="text-lg font-c-sans max-w-xs mx-auto">
  {% if title %}
  <div class="border-b border-gray-300">
    <h1 class="h1">{{ title }}</h1>
  </div>
  {% endif %}
  <form method="post" enctype="multipart/form-data"{% if action_url %} action="{{ action_url }}"{% endif %}> {% csrf_token %}
    {% if next %}
    <input type="hidden" name="next" value="{{ next_url }}">
    {% endif %}
    <div class="space-y-3 mt-5">
      <div class="text-center">
        {% if img.url %}
        <img src="{{ img.url }}" alt="{% if fn %}{{ fn }}{% else %}{{ usr }}{% endif %} {% trans 'Image' %}" class="w-64 h-64 border border-gray-300 rounded-full mx-auto">
        {% else %}
        <svg class="text-gray-600 fill-current"><use xlink:href="{% static 'img/svg-defs.svg' %}#smile"></use></svg>
        {% endif %}
      </div>
      <div>
        <label for="id_img" class="lf">{{ form.img.label }}</label>
        {{ form.img }}
      </div>
      <div>
        <label for="id_first_name" class="lf">{{ form.first_name.label }}</label>
        {{ form.first_name }}
      </div>
      <div>
        <label for="id_last_name" class="lf">{{ form.last_name.label }}</label>
        {{ form.last_name }}
      </div>
    </div>
    <div class="text-center space-y-5 mt-4">
      <a class="text-base text-gray-700 hover:text-gray-900 rounded-xl border border-transparent hover:border-yellow-400 focus:outline-none py-1 px-2" href="{{ psw_change_url }}">{% trans 'Change password' %}</a>
      <button type="submit" class="cbtn">{% trans 'Save' %}</button>
    </div>
  </form>
</div>
{% endblock %}
{#<!-- psw_change_url -> templates/registration/password_change_form.html <label for="email">Email:</label><input type="text" id="email" class="form-control" value="{{ request.user.email }}" disabled="disabled"/><span class="text-gray-700 text-sm">Cannot change email</span> |crispy .as_p -->#}

accounts/templates/accounts/email_activation.html
{% load i18n %}
{% autoescape off %}
Hi{% if user.first_name %} {{ user.first_name }}{% endif %},
{% trans 'Please click on the link to activate your account' %}: https://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/login.html
{% extends 'accounts/register_login_base.html' %}
{% load i18n static %}
{% block title %}{% trans 'Log in' %}{% endblock %}
{% block content %}
<div class="mx-10 my-6">
  {% if form.errors %}
  <p class="text-center bg-white text-red-600 border border-red-600 rounded-xl py-1 px-2 my-4">{% trans 'Email or password invalid' %}</p>
  {% endif %}
  <h1 class="text-2xl m-2">{% trans 'Log in' %}</h1>
  <form method="post"{% if action_url %} {{ action_url }}{% endif %}> {% csrf_token %}
    <div class="space-y-3">
      <div>
        <label for="id_email" class="m-2">{{ form.email.label }}</label>
        {{ form.email }}
      </div>
      <div>
        <label for="id_password" class="m-2">{{ form.password.label }}</label>
        {% comment %}<!-- x-data="{ click: false }" <div class="relative" x-data="{ show: true }"><input :type="show ? 'password' : 'text'" -->{% endcomment %}
        {{ form.password }}
      </div>
    {% comment %}<!--<button @click="show = !show" class="text-xs absolute inset-y-0 right-0 flex items-center px-2 text-gray-600 mr-2 focus:outline-none" type="button">
      <span x-show="show">{% trans 'Show' %}</span>
      <span x-show="!show">{% trans 'Hide' %}</span>
      </button>
    </div>-->{% endcomment %}
    <div class="m-1">
      <a class="text-sm un cr p-1" href="{{ psw_reset_url }}" target="_blank" rel="noopener">{% trans 'Forgot password?' %}</a>
    </div>
    {{ form.captcha }}
    <button id="log" class="cbtn mt-4" type="submit">{% trans 'Continue' %}</button>
  </form>
  <div class="m-1 mt-4">
    <p>{% trans "New to" %} {{ com }}?
      <a href="{{ register_url }}" class="regbtn" target="_blank" rel="noopener">{% trans 'Sign Vp' %}</a>
    </p>
  </div>
</div>
{% endblock%}
{% comment %}<!--{ % include 'accounts/snippets/anti-bot.html' % } if not next_url %}<h1 class="sc text-center font-tex font-bol">Welcome back to {{ com }}</h1>{% endif %}
action="{% if next_url %}{{ next_url }}{% else %}{{ login_url }}{% endif %}"{% if next_url %}
<input type='hidden' name='next' value='{{ next_url }}'> {% csrf_token %}
{% endif % { % blocktranslate % }<p class="text-sm pt-4 ml-1">{% trans 'New?' %} <a href="{{ register_url }}" class="text-yellow-500 hover:text-yellow-400 font-semibold focus:outline-none">Sign up</a></p>{ % block js %}{ % endblock %}
stay sign in for a week passwordless login
<script>
  var reca = document.getElementById('recap').value;
  function onClick(e) {
    e.preventDefault();
    grecaptcha.ready(function() {
      grecaptcha.execute(reca, {action: 'submit'}).then(function(token) {
        console.log(token);
        document.getElementById('g-recaptcha-response').value = token;
      });
    });
  }
</script>
<style> resize h-captcha
#rc-imageselect {transform:scale(0.77);-webkit-transform:scale(0.77);transform-origin:0 0;-webkit-transform-origin:0 0;}
</style>
<script>
  function onSubmit(token) {document.getElementById("reca").submit();}
</script><svg class="fill-current h-4 w-4" data-tippy-content="Show" viewbox="0 0 576 512">
  <use x-show="show" xlink:href="{% static 'img/svg-defs.svg' %}#show-psw"></use>
  <use x-show="!show" xlink:href="{% static 'img/svg-defs.svg' %}#!show-psw"></use>
</svg> -->{% endcomment %}

accounts/templates/accounts/pswless-token.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" media="screen,projection">
  <title>{% trans 'Clavem Login Code' %}</title>
</head>
<body>
  <div class="font-c-sans text-lg">
    {% blocktranslate %}
    <p>Hi,</p>
    <p>Use this code to log in:</p>
    {% endblocktranslate %}
    <p class="border border-gray-300 rounded-lg p-2">{{ callback_token }}</p>
  </div>
</body>
</html>

accounts/templates/accounts/register.html
{% extends 'accounts/register_login_base.html' %}
{% load i18n static widget_tweaks %}
{% block title %}{% trans 'Sign Vp' %}{% endblock %}
{% block content %}
<div x-data="{ click: false }" class="mx-10 my-6">
  <h1 class="text-2xl  m-2">{% trans 'Sign Vp' %}</h1>
  <form method="post"> {% csrf_token %}
    <div class="mb-3">
      <label for="id_email" class="lf">{{ form.email.label }}</label>
      {{ form.email }}
    </div>
    <label for="id_password" class="lf">{{ form.password.label }}</label>
    {% comment %}<!--{% render_field form.email class=form %} <div class="relative" x-data="{ show: true }">
      <input :type="show ? 'password' : 'text'"  -->{% endcomment %}
      {{ form.password }}
    {% comment %}<!-- <button @click="show = !show" class="text-xs absolute inset-y-0 right-0 flex items-center px-2 text-gray-600 mr-2 focus:outline-none" type="button">
      <span x-show="show">{% trans 'Show' %}</span>
      <span x-show="!show">{% trans 'Hide' %}</span>
      </button>
    </div> -->{% endcomment %}
    {% if form.password %}
    <div class="border border-gray-300 bg-white shadow hover:shadow-md rounded-xl mt-5 mb-3">
      <div class="text-sm text-gray-900 py-3 px-2">
      {% comment %}<!-- <details class="space-y-1">
        <summary class="text-lg font-semibold inline-flex items-center">
          <svg class="w-4 h-4 text-gray-500 fill-current mr-2"><use xlink:href="{% static 'img/svg-defs.svg' %}#key"></use></svg>
          {% trans 'Security Tips' %}</summary>
        <ul class="list-disc list-outside pl-5">
          <li>{% trans 'Generate and store passwords with' %} <a class="font-semibold un focus:outline-none" href="https://keepassxc.org/download/">KeePassXC</a>*</li>
          <li>{% trans 'It should have at least 15 characters.' %}</li>
        </ul>
        <p class="text-gray-700 ml-2 mt-1">(*) or whatever tool you <i>trust</i>.</p>
      </details> -->{% endcomment %}
        <p class="text-base font-semibold inline-flex items-center mb-2">
          <svg class="w-4 h-4 text-gray-500 fill-current mr-2"><use xlink:href="{% static 'img/svg-defs.svg' %}#key"></use></svg>
          {% trans 'Security Tips' %}
        </p>
        <ul class="list-disc list-outside pl-5">
          <li>{% trans 'Generate and store passwords with' %} <a class="font-semibold un focus:outline-none" href="https://keepassxc.org/download/" target="_blank" rel="noopener">KeePassXC</a>*</li>
          <li>{% trans 'It should have at least 15 characters.' %}</li>
          {% comment %}<!--<li>Download <a class="font-semibold un focus:outline-none" href="https://freeotp.github.io/">FreeOTP</a>* and add <a class="font-semibold un focus:outline-none" href="{{ 2fa_url }}">2-factor authentication</a></li>-->{% endcomment %}
        </ul>
        <p class="text-gray-600 ml-2 mt-1">(*) or whatever tool you <i>trust</i>.</p>
      </div>
    </div>
    {% endif %}
    {{ form.captcha }}
    <div class="text-sm py-2 px-1">{% trans 'Please read the' %}
      <a href="{{ privacy_url }}" class="polbtn un" target="_blank" rel="noopener" data-tippy-content="Your rights">Privacy</a> {% trans 'and' %}
      <a href="{{ terms_url }}" class="polbtn un" target="_blank" rel="noopener" data-tippy-content="{{ com }}'s rights">Terms</a> {% trans 'policies before signing up.' %}
    </div>
    <button @click="click=!click" class="cbtn" type="submit">
      <p x-show="!click">{% trans 'Create account' %}</p>
    </button>
  </form>
  <p class="m-1 mt-4">{% trans 'Have an account?' %}
    <a href="{{ login_url }}" class="regbtn" target="_blank" rel="noopener">{% trans 'Log In' %}</a>
  </p>
</div>
{% endblock%}
{% comment %}<!--Show errors<fieldset><legend> <p x-show="click">{% trans 'Sending verification email' %}</p>
Signing up means you read and agreed to our By signing up, you agree to the { { com }} Privacy Policy and Terms of Service. <svg class="fill-current h-4 w-4" viewbox="0 0 576 512">
  <use x-show="show" xlink:href="{% static 'img/svg-defs.svg' %}#show-psw"></use>
  <use x-show="!show" xlink:href="{% static 'img/svg-defs.svg' %}#!show-psw"></use>
</svg>
<a class="font-semibold un focus:outline-none focus:shadow-outline" href="{ { cookie_url }}" data-tippy-content="Your rights">Cookie</a>
% if next_url %}<input type="hidden" name="next" value="{ { next_url }}"> { % csrf_token %}{ % endif %}
take 5 minutes to
{ % if not next_url %}<h1 class="sc text-center text-gray-800 font-semibold"></h1>{ % endif %}
{ % trans 'Welcome to' %} {{ com }} id="log"{ % include 'accounts/snippets/anti-bot.html' %}2-step auth Add 2fa page <li>Ab(3</li><li>Your password must be different from your personal information.</li> data-sitekey="{ { recaptchav3 }}"
data-theme="dark" data-size="compact" class="g-recaptcha border-2 bg-blue-500 border-blue-500 hover:bg-blue-600 hover:border-blue-600 text-white py-1 px-2 text-xs uppercase" data-sitekey="6Lc6dr0UAAAAAMXGDZCOYPE-ncRlu9uQXgA-06t5" data-callback="onSubmit" data-action="submit"
<div class="m-2 mb-5 h-captcha" data-sitekey="d7fbaf1d-fc21-41e9-9e9d-5555b16a7eba" data-error-callback="onError"></div>href="https://bitwarden.com/#download">Bitwarden href="https://authy.com/features/">Authy</a> include 'accounts/snippets/captcha.html' <input class="mr-2 leading-tight" type="checkbox"><span class="text-sm">Send me your newsletter.</span></label>-->{% endcomment %}

accounts/templates/accounts/register_login_base.html
{% load i18n meta static %}
{% url 'home:home' as home_url %}
{% url 'home:cookie' as cookie_url %}
{% url 'home:privacy' as privacy_url %}
{% url 'home:terms' as terms_url %}
{% url 'register' as register_url %}
{% url 'login' as login_url %}
{% url 'password_change' as psw_change_url %}
{% url 'password_reset' as psw_reset_url %}
{% url '2fa_auth' as 2fa_url %}
{% with com='Clavem' url='www.clavem.co' %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:'en-us' }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
<head {% meta_namespaces %}>
  {% include 'base/snippets/head.html' %}
  <title>{% block title %}{% endblock %} · {{ com }}</title>
</head>
<body class="bg-primary">
  <div id="nojs" class="max-w-xs py-16 mx-auto">
    {% include 'base/snippets/message.html' %}
    <div class="font-c-sans border border-gray-300 shadow-md bg-footer text-black text-lg rounded-xl">
      <div class="mt-8">
        <svg class="animate-pulse s w-24 h-24 fill-current mx-auto"><use xlink:href="{% static 'img/svg-defs.svg' %}#clogo"></use></svg>
      </div>
      {% block content %}{% endblock %}
    </div>
  </div>
  {% include 'base/noscript.html' %}
  <script rel="preload" type="text/javascript" src="{% static 'js/popper-2.9.1.min.js' %}"></script>
  {% include 'base/snippets/tippy.html' %}
  {% block js %}{% endblock %}
</body>
</html>
{% endwith %}
{% comment %}<!--<base target="_blank" rel="noopener"> { % include 'base/js.html' %}<a href="{ { home_url }}"></a> https://asciinema.org/login/new passwordless recaptchav3='6LcicwYaAAAAAKyAuNUO8ZJK_epWL5dzZdyoDdnS' oncontextmenu="return false" onkeydown="return true;" onmousedown="return true;"
{ % with HCAPTCHA_SECRET_KEY='d7fbaf1d-fc21-41e9-9e9d-5555b16a7eba' %}<script src="https://hcaptcha.com/1/api.js" async defer></script><script src="{ % static 'js/hcaptcha.js' %}"></script>
<script src="https://assets.hcaptcha.com/captcha/v1/88f8cd7/hcaptcha.js" integrity="sha384-VEF/+ve5fSbrXhXJ0k8p/QznSGTj0vaxJjC5eG6/YL4X4Tumcooelh0RAFuTIj18" crossorigin="anonymous"></script>
<script src="https://www.google.com/recaptcha/api.js?render=6LcQrKsZAAAAAO-qIYwbGmhmnL2O_MyHYc6x8nwE"></script>
<script>grecaptcha.ready(function(){$('#rlform').submit(function(e){var form = this;e.preventDefault()grecaptcha.execute('6LcQrKsZAAAAAO-qIYwbGmhmnL2O_MyHYc6x8nwE', {action: 'rlform'}).then(function(token){$('#recaptcha').val(token)form.submit})})})</script>
<div class="p-2 pt-0 h-captcha" data-sitekey="d7fbaf1d-fc21-41e9-9e9d-5555b16a7eba"></div>-->{% endcomment %}