chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.contact, name="contact"),
    # views.ContactView.as_view(), name="contact"),
    path("<str:room>/", views.room, name="room"),
]

shorturl/hostsconf/urls.py
from django.urls import include, path, re_path

from .views import wildcard_redirect

urls_patterns = [
    re_path(r"(?P<path>.*)", wildcard_redirect),
]

shorturl/urls.py
from django.urls import path, re_path
from . import views

app_name = "shorturl"

urlpatterns = [
    path("", views.ShortURLView.as_view(), name="curl"),
    # only for admin
    re_path(r"^(?P<shortcode>[\w-]+)/$", views.URLRedirectView.as_view(), name="code"),
    # models.get_short_url
]

shorturl/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_hosts.resolvers import reverse

# from analytics.models import ClickEvent
from core.utils import create_shortcode

from .validators import validate_url  # validate_dotcom_url,

SHORTCODE_MAX = getattr(settings, "SHORTCODE_MAX", 7)
# URL = getattr(settings, "BASE_URL", "https://www.clavem.co")


class ClUrlManager(models.Manager):
    def all(self, *args, **kwargs):
        qs = super(ClUrlManager, self).all(*args, **kwargs).filter(active=True)
        return qs

    def refresh_shortcodes(self, items=None):
        qs = ClUrl.objects.filter(id__gte=1)
        if items is not None and isinstance(items, int):
            qs = qs.order_by("-id")[:items]
        new = 0
        for q in qs:
            q.shortcode = create_shortcode(q)
            q.save()
            new += 1
        return _(f"New codes created {new}")


class ClUrl(models.Model):
    url = models.CharField(
        max_length=240, validators=[validate_url]  # , validate_dotcom_url
    )
    # clicks = models.ForeignKey()
    shortcode = models.CharField(max_length=SHORTCODE_MAX, unique=True, blank=True)
    # null=False
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ClUrlManager()

    class Meta:
        verbose_name = _("Clvm short URL")
        verbose_name_plural = _("Clvm short URLs")
        ordering = ["-updated"]

    def __str__(self):
        return str(self.url)

    def save(self, *args, **kwargs):
        if self.shortcode is None or self.shortcode == "":
            self.shortcode = create_shortcode(self)
        url = self.url
        # if not "https" in url:
        #     url = "https://" + url
        # print("* ", url)
        super(ClUrl, self).save(*args, **kwargs)

    def get_short_url(self):
        url_path = reverse(
            "clvm:code",
            kwargs={"shortcode": self.shortcode},  # , host="www", scheme="http"
        )  # , port="8000"
        return url_path

shorturl/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .validators import validate_url


class SubmitURLForm(forms.Form):
    url = forms.CharField(
        label="URL",  # _("Submit URL"),
        widget=forms.TextInput(
            attrs={
                # "placeholder": _("Original URL"),
                "class": "w-full flex border border-gray-300 focus:border-yellow-500 rounded-xl shadow focus:outline-none focus:ring-2 focus:ring-yellow-200 focus:ring-offset-transparent focus:ring-offset-2 py-1 px-2",
            }
        ),
        validators=[validate_url],
    )

    # def clean(self):
    #     url = self.cleaned_data.get("url")#cleaned_data["url"]
    #     if "http" in url:
    #         url = url.replace("http://www.", "")
    #     return url

    #     cleaned_data = super(SubmitURLForm, self).clean()
    #     url = cleaned_data["url"]

    # def clean_url(self):
    #     url = self.cleaned_data["url"]
    #     if "http" in url:
    #         return url
    #     return "http://" + url
    #     url_validator = URLValidator()
    #     try:
    #         url_validator(url)
    #     except:
    #         raise forms.ValidationError(_("Please submit a valid URL"))
    #     return url

shorturl/hostsconf/views.py
from django.conf import settings
from django.http import HttpResponseRedirect

DEFAULT_REDIRECT_URL = getattr(settings, "DEFAULT_REDIRECT_URL", "www.clavem.co")#http://


def wildcard_redirect(request, path=None):
    new_url = DEFAULT_REDIRECT_URL
    print("*** ", getattr(settings, "DEFAULT_REDIRECT_URL", "www.clavem.co"))
    if path is not None:
        new_url += "/" + path
    return HttpResponseRedirect(new_url)

shorturl/views.py
from analytics.models import ClickEvent
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from django.http import Http404  # HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404

# from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View

from .forms import SubmitURLForm
from .models import ClUrl


class ShortURLView(LoginRequiredMixin, View):
    # permission_denied_message = _("You do not have enough access privileges.")
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if not request.user.is_admin or not request.user.is_staff:
                raise PermissionDenied
        else:
            raise PermissionDenied
        form = SubmitURLForm
        context = {"title": "CLVM URL Shortener", "form": form}
        return render(request, "shorturl/shorturl.html", context)

    def post(self, request, *args, **kwargs):
        form = SubmitURLForm(request.POST)
        context = {"title": "CLVM URL Shortner", "form": form}
        template = "shorturl/shorturl.html"
        if form.is_valid():
            new_url = form.cleaned_data.get("url")
            obj, created = ClUrl.objects.get_or_create(url=new_url)
            # context = {"object": obj, "created": created}
            print("##### ", obj)
            if created:
                context = {
                    "title": _("Short URL Created"),
                    "object": obj,
                    "created": created,
                }
                template = "shorturl/shorturl-done.html"
            else:
                context = {"title": _("Short URL exists"), "object": obj}
                template = "shorturl/shorturl-exists.html"
        return render(request, template, context)


class URLRedirectView(View):
    def get(self, request, shortcode=None, *args, **kwargs):
        # obj = get_object_or_404(ClUrl, shortcode=shortcode)
        qs = ClUrl.objects.filter(shortcode=shortcode)
        if qs.count() != 1 and not qs.exists():
            raise Http404
        obj = qs.first()
        ClickEvent.objects.create_event(obj)  # clicks
        return redirect(obj.url)  # HttpResponseRedirect

shorturl/templates/shorturl/shorturl-done.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% if title %}{{ title }}{% else %}{% trans 'URL Shortner' %}{% endif %}{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="wxs">
  <div class="bordb mb-4 xl:mr-6">
    <h1 class="h1">{% if title %}{{ title }}{% else %}{% trans 'Short URL Created' %}{% endif %}</h1>
  </div>
  <a href="{{ object.get_short_url }}" class="block bt cr2">{{ object.get_short_url }}</a>
</div>
{% endif %}
{% endblock %}{#<!-- <p>{ { object.url }}</p> -->#}

shorturl/templates/shorturl/shorturl-exists.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% if title %}{{ title }}{% else %}{% trans 'URL Shortner' %}{% endif %}{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="wxs">
  <div class="bordb mb-4 mr-6">
    <h1 class="h1">{% if title %}{{ title }}{% else %}{% trans 'Short URL Exists' %}{% endif %}</h1>
  </div>
  {% if object.clickevent %}<p>Clicks: {{ object.clickevent.count }}</p>{% endif %}
  <a href="{{ object.get_short_url }}" class="block bt cr2 my-4">{{ object.get_short_url }}</a>
  <a href="{{ short_url }}" class="text-lg text-center inline-flex items-center bg-gradient-to-tr to-yellow-300 from-yellow-400 hover:to-yellow-300 hover:from-yellow-500 border-2 border-yellow-300 cr2 py-1 px-2">
    <svg class="fill-current w-4 h-4 mr-2"><use xlink:href="{% static 'img/svg-defs.svg' %}#add"></use></svg>
    {% trans 'Add new' %} URL
  </a>
</div>
{% endif %}
{% endblock %}

shorturl/templates/shorturl/shorturl.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% if title %}{{ title }}{% else %}{% trans 'URL Shortner' %}{% endif %}{% endblock %}
{% block content %}
<div class="wxs">
{% if request.user.is_authenticated and request.user.is_admin or request.user.is_staff %}
  <div class="bordb mb-4">
    <h1 class="h1">{% if title %}{{ title }}{% else %}{% trans 'URL Shortner' %}{% endif %}</h1>
  </div>
  <form method="post"{% if action_url %} action="{{ action_url }}"{% endif %}> {% csrf_token %}
    <label for="id_url" class="text-gray-700 m-1">{{ form.url.label }}</label>
    {{ form.url }}
    <input type="submit" value="{% trans 'Shorthen' %}" class="w-full cursor-pointer bg-gradient-to-tr to-yellow-300 from-yellow-400 hover:to-yellow-300 hover:from-yellow-500 cr2 px-2 py-1 mt-6">
  </form>
{% else %}
  <div>
    <p class="text-center mt-8">{% trans 'Please ' %}<a href="{{ login_url }}?next={{ request.get_full_path|urlencode }}" class="text-yellow-500 hover:text-yellow-600 font-semibold focus:outline-none">{% trans 'log in' %}</a>{% trans ' to access this page.' %}</p>
  </div>
{% endif %}
</div>
{% endblock %}